#!/usr/bin/env node
/**
 * generate-css.mjs — Dev-time CSS generator for premium CSS library.
 *
 * Purpose:
 *   Bundles `src/core/style/premiumCss.ts` via esbuild (no new dependency —
 *   esbuild is already in node_modules via Vite), invokes every static
 *   builder function, and writes the concatenated CSS to
 *   `src/styles/premium-generated.css`. The output is committed to the repo
 *   (Bapak-approved Option B), then imported by `src/styles.css`.
 *
 * Why bundle (not strip-types):
 *   `premiumCss.ts` uses extensionless TS imports (`../style-packs/...`),
 *   which Node's experimental strip-types cannot resolve. esbuild handles
 *   both type-stripping and import resolution in one step, and is already
 *   installed transitively via Vite.
 *
 * Why per-function calls (no buildAllStaticCss()):
 *   Per Bapak directive: callers must invoke functions explicitly so each
 *   function is independently auditable and tree-shakeable. The generator
 *   script — by definition — must call every static function (otherwise the
 *   generated file would be incomplete), so it explicitly enumerates them.
 *
 * Usage:
 *   npm run generate:css
 *
 * Output:
 *   src/styles/premium-generated.css  (overwritten on every run)
 *
 * Post-conditions for caller:
 *   - File always ends with a trailing newline.
 *   - File always has a header comment so reviewers know it's generated.
 *   - Empty body (all functions return '') is a valid state during scaffolding.
 */

import esbuild from 'esbuild';
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, '..');

const sourceFile = resolve(repoRoot, 'src/core/style/premiumCss.ts');
const outputFile = resolve(repoRoot, 'src/styles/premium-generated.css');
const tmpFile = resolve(repoRoot, 'node_modules/.tmp/premium-css-bundle.mjs');

console.log('[generate-css] Bundling', sourceFile);

// Step 1: Bundle premiumCss.ts (and its type-only deps) into a single ESM file.
const buildResult = await esbuild.build({
  entryPoints: [sourceFile],
  bundle: true,
  format: 'esm',
  platform: 'node',
  write: false,
  outfile: 'bundle.mjs', // virtual name; only used in outputFiles metadata
  logLevel: 'warning',
});

if (buildResult.errors.length > 0) {
  console.error('[generate-css] esbuild reported errors:');
  for (const e of buildResult.errors) console.error('  -', e.text);
  process.exit(1);
}

if (buildResult.outputFiles.length === 0) {
  console.error('[generate-css] esbuild produced no output files.');
  process.exit(1);
}

// Step 2: Write the bundled JS to a temp file we can import.
mkdirSync(dirname(tmpFile), { recursive: true });
writeFileSync(tmpFile, buildResult.outputFiles[0].text);

// Step 3: Import the bundle and call every static builder function.
//         (Group 7 — buildPremiumHeroCss / buildPremiumSkinCss — is parameterised
//          and only emitted by export-html.ts at runtime; the static CSS file
//          does not include skin-specific output.)
let premiumCss;
try {
  // Cache-bust query to force re-import across runs.
  premiumCss = await import(tmpFile + '?t=' + Date.now());
} finally {
  // Always remove the temp file, even on import failure.
  rmSync(tmpFile, { force: true });
}

const sections = [
  { name: 'Group 1 — Animations',           fn: 'buildAnimationsCss' },
  { name: 'Group 2 — Cover decoration',     fn: 'buildCoverDecorationCss' },
  { name: 'Group 3 — Background patterns',  fn: 'buildBackgroundPatternCss' },
  { name: 'Group 4 — Premium block panel',  fn: 'buildPremiumBlockCss' },
  { name: 'Group 5 — Celebration effects',  fn: 'buildCelebrationCss' },
  { name: 'Group 6 — Choice defaults + identical skins', fn: 'buildMiscIdenticalCss' },
];

const chunks = [];
const header = [
  '/* ==========================================================================',
  ' * AUTO-GENERATED by scripts/generate-css.mjs — DO NOT EDIT BY HAND.',
  ' *',
  ' * Source: src/core/style/premiumCss.ts',
  ' * Regenerate with: npm run generate:css',
  ' *',
  ' * This file is imported by src/styles.css at the TOP per CSS spec',
  ' * (Vite warns otherwise). export-html.ts does NOT import this file;',
  ' * it imports premiumCss.ts functions directly (per Bapak directive).',
  ' * Specificity ties are not a concern: each migrated rule is REMOVED from',
  ' * styles.css in the same commit it is added to premiumCss.ts, so there',
  ' * are no duplicate definitions in steady state.',
  ' * ==========================================================================',
  ' */',
  '',
].join('\n');
chunks.push(header);

let totalBytes = 0;
for (const section of sections) {
  const fn = premiumCss[section.fn];
  if (typeof fn !== 'function') {
    console.error('[generate-css] Missing export:', section.fn);
    process.exit(1);
  }
  const css = String(fn() ?? '').trim();
  totalBytes += css.length;

  if (css.length > 0) {
    chunks.push(`/* ${section.name} */`);
    chunks.push(css);
    chunks.push(''); // blank line separator
  } else {
    // Keep a marker so reviewers can see the section is wired but empty
    // (scaffolding phase). Once Commit 2 fills it, the marker disappears.
    chunks.push(`/* ${section.name} — (empty, scaffolding) */`);
    chunks.push('');
  }
}

const output = chunks.join('\n').replace(/\n{3,}/g, '\n\n') + '\n';

mkdirSync(dirname(outputFile), { recursive: true });
writeFileSync(outputFile, output);

console.log('[generate-css] Wrote', outputFile);
console.log('[generate-css] Total non-empty CSS bytes:', totalBytes);
console.log('[generate-css] Output file size:', output.length, 'bytes');
